name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_HTTP_TIMEOUT: 240
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install packages
      run: sudo apt-get -y install cmake libpq-dev python3-dev libssl-dev libffi-dev pbzip2
    - name: Install pipenv
      run: python -m pip install --upgrade pip && pip -q install pipenv --upgrade
    - name: Clone emwiki-contents
      run: git clone https://github.com/mimosa-project/emwiki-contents.git ./emwiki/emwiki-contents
    - name: Decompress mmlfiles
      run: sh decompress.sh
      working-directory: ./emwiki/mmlfiles
    - name: Build emparser
      run: pipenv install && pipenv run python setup.py build
      working-directory: ./emparser
    - name: Install python dependencies
      run: pipenv sync --dev
    - name: Install npm dependencies
      run: npm install
    - name: Create docker containers for development
      run: docker-compose up -d
    - name: Migrate
      run: pipenv run python ./emwiki/manage.py migrate
    - name: Load article data to database
      run: pipenv run python ./emwiki/manage.py load_articles
    - name: Load symbol data to database
      run: pipenv run python ./emwiki/manage.py load_symbols
    - name: Check codestyle
      run: |
         pipenv run flake8
         npx eslint "./emwiki/**/*.js"
    - name: Test
      run: |
         pipenv run coverage run
         pipenv run coverage report
      working-directory: ./emwiki
    - name: Check django deployment settings
      run: pipenv run python ./emwiki/manage.py check --deploy
